const falseUrgencyIndicators = [
  "limited-time offer",
  "only \\d+ items left",
  "exclusive deal",
  "don't miss out",
  "act now",
  "hurry, offer ends soon",
  "sale ends today",
  "last chance",
  "offer expires",
  "get it before it's gone",
  "while supplies last",
  "deal of the day",
  "special promotion",
  "today only",
  "flash sale",
  "time-limited offer",
  "limited stock available",
  "expires at midnight",
  "early bird special",
  "final hours",
  "instant savings",
  "guaranteed",
  "unbeatable",
  "never before seen",
  "exclusive offer",
  "won't believe your eyes",
  "one-time offer",
  "don't wait",
  "new lower price",
  "lowest price ever",
  "price drop",
  "today's deal",
  "clearance",
  "going out of business",
  "liquidation",
  "everything must go",
  "50% off (or more)",
  "special discount",
  "secret sale",
  "hidden offer",
  "urgent",
  "don't delay",
  "must end soon",
  "limited quantity",
  "instant rebate",
  "member only",
  "new offer every day",
  "lowest price guaranteed",
  "exclusive access",
  "free gift",
  "bonus",
  "double your order",
  "order today and get a free gift",
  "risk-free",
  "money-back guarantee",
  "100% satisfaction guarantee",
  "no obligation",
  "no strings attached",
  "cancel anytime",
  "terms and conditions apply",
  "see website for details",
  "claim your discount",
  "secret code",
  "act fast",
  "don't hesitate",
  "final sale",
  "limited time only",
  "exclusively for you",
  "get yours now",
  "instant approval",
  "reserve now",
  "confirm your order",
  "unlock savings",
  "offer ends tonight",
  "buy now, pay later",
  "limited-time price",
  "insider access",
  "exclusive early access",
  "first come, first served",
  "for a limited time only",
  "don't pass up",
  "special introductory offer",
  "exclusive member deal",
  "vip offer",
  "pre-sale",
  "invitation-only",
  "exclusive pre-launch",
  "limited-time bonus",
  "exclusive savings",
  "get exclusive access",
  "never to be repeated",
  "only available to subscribers",
  "24-hour special",
  "today's exclusive",
  "deal expires tonight",
  "midnight madness sale",
  "special 1-day offer",
  "early access deal",
  "today's featured deal",
  "limited-time surprise",
  "exclusive flash event",
  "members-only flash sale",
  "exclusive weekend pricing",
  "secret member discount",
  "limited-time app offer",
  "exclusive app deal",
  "today's secret sale",
  "early bird savings",
  "limited-time member price",
  "exclusive holiday offer",
  "limited-time holiday deal",
  "VIP holiday sale",
  "exclusive Black Friday savings",
  "Cyber Monday special",
  "12 Days of Deals",
  "limited-time winter sale",
  "holiday countdown offer",
  "today's holiday surprise",
  "exclusive New Year deal",
  "limited-time Valentine's Day offer",
  "spring clearance event",
  "summer flash sale",
  "back-to-school special",
  "fall exclusive deal",
  "holiday gift guide special",
  "today's exclusive anniversary offer",
  "limited-time birthday discount",
  "exclusive loyalty member deal",
  "limited-time reward member offer",
  "today's loyalty program special",
  "exclusive referral program discount",
  "limited-time friend referral offer",
  "exclusive social media follower deal",
  "today's Twitter/Facebook/Instagram offer",
  "limited-time email subscriber special",
  "today's newsletter subscriber deal",
];

var checkForFalseUrgency = function (content, filtered_elements) {
  for (var i = 0; i < falseUrgencyIndicators.length; i++) {
    var indicator = new RegExp(falseUrgencyIndicators[i], "i");

    if (indicator.test(content)) {
      // Find the index of the element in filtered_elements array
      var index = filtered_elements.findIndex((element) =>
        indicator.test(element)
      );

      return index; // Return the index if found
    }
  }
  return -1; // Return -1 if no false urgency indicators found
};
